name: Tests
on: [push]
jobs:
  php-unit-and-functional-tests:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true
      matrix:
        php-versions: ['8.1']
    services:
      db:
        image: postgres
        env:
          POSTGRES_PASSWORD: pa$$word
          POSTGRES_DB: textmagic_test
        ports:
          - 5432/tcp
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Git checkout placeholder-service
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer:v2
          extensions: mbstring, xml, ctype, iconv, intl, dom, iconv, mbstring, pdo_pgsql
        env:
          update: true
      - name: Check PHP Version
        run: php -v
      - name: Install Composer dependencies
        run: composer install
      - name: Run functional and unit tests
        env:
          POSTGRES_PASSWORD: secret
          POSTGRES_USER: postgres
          DATABASE_URL: pgsql://postgres:pa$$word@127.0.0.1:5432/textmagic_test
          APP_ENV: test
        run: |
          bin/console do:da:cr
          bin/console do:mi:mi -n
          bin/phpunit